### ISSUE TITLE
Unable to retrieve data error in Show List and Add New Show

### ISSUE THREAD

**Issue by hugepants** [Hiltronix/plugin.video.sickrage#4]
Hi
Thanks for continuing work on this addon.

I'm using version 1.3.3 with SickRage 4.0.29 and I get `Error: expected string or buffer` when trying to load the Show List and adding a new show.

I see that a URL and API key has been hardcoded [here](https://github.com/Hiltronix/plugin.video.sickrage/blob/433e45eab40ab1d5d7b2c1743547e18f043b99e8/resources/lib/sickbeard.py#L72), I edited it to my URL/API and it seems to work for now.

Thanks

**Comment by Hiltronix** [comment]
Hi,

Thanks for the heads up.  It's a lame mistake on my part.  I hard coded 
it when I was originally testing the function, and forgot to change it 
back.  It should work correctly if you update to v.1.3.4. Since the hard 
coded API key was my own, I didn't notice the problem.

Please let me know if there is still an issue.

On 2015-08-15 4:26 PM, hugepants wrote:

> Hi
> Thanks for continuing work on this addon.
> 
> I'm using version 1.3.3 with SickRage 4.0.29 and I get |Error: 
> expected string or buffer| when trying to load the Show List and 
> adding a new show.
> 
> I see that a URL and API key has been hardcoded here 
> https://github.com/Hiltronix/plugin.video.sickrage/blob/master/resources/lib/sickbeard.py#L72, 
> I edited it to my URL/API but I still get the error.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Hiltronix/plugin.video.sickrage/issues/4.

## 

Hiltronix Computer Services
Winnipeg, Manitoba, Canada

**Comment by hugepants** [comment]
No problem, thanks for fixing it so quickly. I've updated to 1.3.4 and it's working again.
